### ISSUE TITLE
garbage collection on computedObservers

### ISSUE THREAD

**Issue by danielweck** [tomasklaen/statin#3]
I believe this property only exists to retain `computedObserver` in memory once the function returns? (i.e. in case `registerDependency(computedObserver)` is not called yet)

https://github.com/tomasklaen/statin/blob/d9d35e3def67b60a663a3afc4d6f2ab8f8b9c5ff/src/index.ts#L348

May I suggest adding a code comment to clarify, and/or adjust the TypeScript type to reflect the existance of this property?

**Comment by tomasklaen** [comment]
Oh no no, `computedObserver` is owned by `get()`, so it's not gonna be garbage collected.

This is probably just some leftover line I forgot to remove after debugging something, embarrassing 😅.
