### ISSUE TITLE
edit() causes a signal "read", yet described as accessor of raw value

### ISSUE THREAD

**Issue by danielweck** [tomasklaen/statin#4]
https://github.com/tomasklaen/statin#signaledit

The example given is:

```javascript
const set = signal(new Set<string>());

// Mutates the set and sends changed signal afterwards
set.edit((set) => set.add('foo'));

// This is essentially just a shorthand for
set.value.add('foo');
set.changed();
```

... in particular, I think that this statement is not quite correct:

```javascript
// This is essentially just a shorthand for
set.value.add('foo');
```

...because in fact behind the scenes a signal "read()" occurs:

```javascript
set().add('foo');
```

...see the code under the hood:

https://github.com/tomasklaen/statin/blob/d9d35e3def67b60a663a3afc4d6f2ab8f8b9c5ff/src/index.ts#L270-L273

...which registers a dependency "on itself":

https://github.com/tomasklaen/statin/blob/d9d35e3def67b60a663a3afc4d6f2ab8f8b9c5ff/src/index.ts#L276-L279

So, I am wondering whether the "edit" code should become:

```javascript
	getSet.edit = (editor: (value: T) => void) => {
		editor(getSet.value);
		getSet.changed();
	};
```

(`editor(getSet.value);` instead of `editor(read());`)

Could you please clarify whether the `read()` is intentional in your current logic (and if so what is the rationale), or simply an oversight of something that doesn't cause any problems at runtime?

UPDATE: I wrote a unit test in my Statin fork to check that `signal.edit()`  used in a `reaction()` does indeed trigger a self re-evaluation when the signal is mutated from outside. Conversely, `signal.write(value)` / `signal(value)` doesn't, which is inconsistent.

**Comment by tomasklaen** [comment]
Yes, you're absolutely right :) Making edit read was an oversight.

Again, thank you so much for the code review!
